steps:
  - name: 'hashicorp/terraform:1.6.6'
    args: ['init']
    dir: 'IaC/modules/composer'
    
  - name: 'hashicorp/terraform:1.6.6'
    args: ['apply', '-compact-warnings', '-auto-approve', '-var-file=../../environments/dev/main.tfvars']
    id: 'env-creation'
    env:
    - 'COMPOSER_BUCKET_NAME=$COMPOSER_BUCKET_NAME'
    dir: 'IaC/modules/composer'

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['cp', 'Codigo/Composer/dag_dq.py', 'gs://$COMPOSER_BUCKET_NAME/dags/dag.py']
    waitFor: ['env-creation']

  
