steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['builds', 'submit', '--config', 'IaC/modules/apis/cloudbuild.yaml', '.']
    id: 'enable_apis'

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['builds', 'submit', '--config', 'IaC/modules/storage/cloudbuild.yaml', '.']
    id: 'storage'
    waitFor: ['enable_apis']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['builds', 'submit', '--config', 'IaC/modules/dataplex_lake/cloudbuild.yaml', '.']
    id: 'dataplex_lake'
    waitFor: ['enable_apis']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['builds', 'submit', '--config', 'IaC/modules/service_account/cloudbuild.yaml', '.']
    id: 'service_account'
    waitFor: ['enable_apis']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['builds', 'submit', '--config', 'IaC/modules/bigquery/cloudbuild.yaml', '.']
    id: 'bigquery'
    waitFor: ['enable_apis']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['builds', 'submit', '--config', 'IaC/modules/function/cloudbuild.yaml', '.']
    id: 'functions'
    waitFor: ['service_account']

  # - name: 'gcr.io/cloud-builders/gcloud'
  #   args: ['builds', 'submit', '--config', 'IaC/modules/composer/cloudbuild.yaml', '.']
  #   id: 'composer-env'
  #   waitFor: ['service_account']

  # - name: 'gcr.io/cloud-builders/gcloud'
  #   args: ['builds', 'submit', '--config', 'Codigo/Composer/CI-CD/cicd_config_dags.yaml', '.']
  #   id: 'composer_dags'
  #   waitFor: ['composer-env']    

timeout: '3600s'