steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['builds', 'submit', '--config', 'IaC/modules/apis/cloudbuild.yaml', '.']
    id: 'build-0'

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['builds', 'submit', '--config', 'IaC/modules/pubsub/cloudbuild.yaml', '.']
    id: 'build-1'
    waitFor: ['build-0']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['builds', 'submit', '--config', 'IaC/modules/service_account/cloudbuild.yaml', '.']
    id: 'build-2'
    waitFor: ['build-0']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['builds', 'submit', '--config', 'IaC/modules/storage/cloudbuild.yaml', '.']
    id: 'build-3'
    waitFor: ['build-2']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['builds', 'submit', '--config', 'IaC/modules/dataplex_lake/cloudbuild.yaml', '.']
    id: 'build-4'
    waitFor: ['build-2']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: check-changes-qae
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if git diff --quiet HEAD^ -- Codigo/QAE; then
          echo "No hay cambios en Codigo/QAE. No se ejecutará el paso de compilación."
        else
          echo "Se detectaron cambios en Codigo/QAE. Se ejecutará el paso de compilación."
          gcloud builds submit --config Codigo/QAE/CI-CD/cicd_qae.yaml .
        fi
    waitFor: ['build-2']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: check-changes-qid
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if git diff --quiet HEAD^ -- Codigo/QID; then
          echo "No hay cambios en Codigo/QID. No se ejecutará el paso de compilación."
        else
          echo "Se detectaron cambios en Codigo/QID. Se ejecutará el paso de compilación."
          gcloud builds submit --config Codigo/QID/CI-CD/cicd_qid.yaml .
        fi
    waitFor: ['build-2']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: check-changes-yml-publisher
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if git diff --quiet HEAD^ -- Codigo/YML_Publisher; then
          echo "No hay cambios en Codigo/YML_Publisher. No se ejecutará el paso de compilación."
        else
          echo "Se detectaron cambios en Codigo/YML_Publisher. Se ejecutará el paso de compilación."
          gcloud builds submit --config Codigo/YML_Publisher/CI-CD/cicd_yml_publisher.yaml .
        fi
    waitFor: ['build-2']

  # - name: 'gcr.io/cloud-builders/gcloud'
  #   args: ['builds', 'submit', '--config', 'Codigo/QAE/CI-CD/cicd_qae.yaml', '.']
  #   id: 'build-5'
  #   waitFor: ['build-2']

  # - name: 'gcr.io/cloud-builders/gcloud'
  #   args: ['builds', 'submit', '--config', 'Codigo/QID/CI-CD/cicd_qid.yaml', '.']
  #   id: 'build-6'
  #   waitFor: ['build-2']

  # - name: 'gcr.io/cloud-builders/gcloud'
  #   args: ['builds', 'submit', '--config', 'Codigo/YML_Publisher/CI-CD/cicd_yml_publisher.yaml', '.']
  #   id: 'build-7'
  #   waitFor: ['build-2']

  