steps:
  # Verifica si el directorio del repositorio ya existe.
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd diegucci-dq
        git pull origin main

  - name: 'hashicorp/terraform:latest'
    args:
      - 'init'
    dir: 'IaC'


  - name: 'hashicorp/terraform:latest'
    args:
      - 'apply'
      - '-auto-approve'
      - '-var-file=diegucci-dq/IaC/environments/dev/main.tfvars'
    dir: 'IaC'