steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['builds', 'submit', '--config', 'IaC/modules/apis/cloudbuild.yaml', '.']
    id: 'build-0'

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['builds', 'submit', '--config', 'IaC/modules/pubsub/cloudbuild.yaml', '.']
    id: 'build-1'
    waitFor: ['build-0']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['builds', 'submit', '--config', 'IaC/modules/service_account/cloudbuild.yaml', '.']
    id: 'build-2'
    waitFor: ['build-0']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['builds', 'submit', '--config', 'IaC/modules/storage/cloudbuild.yaml', '.']
    id: 'build-3'
    waitFor: ['build-2']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['builds', 'submit', '--config', 'IaC/modules/dataplex_lake/cloudbuild.yaml', '.']
    id: 'build-4'
    waitFor: ['build-2']

  - name: Check for changes in Codigo/QAE directory
    id: check-changes-qae
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if git diff --quiet HEAD^ -- Codigo/QAE; then
          echo "::set-output name=changes::false"
        else
          echo "::set-output name=changes::true"
        fi

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['builds', 'submit', '--config', 'Codigo/QAE/CI-CD/cicd_qae.yaml', '.']
    id: 'build-5'
    waitFor: ['build-2']
    condition: steps.check-changes-qae.outputs.changes == 'true'

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['builds', 'submit', '--config', 'Codigo/QID/CI-CD/cicd_qid.yaml', '.']
    id: 'build-6'
    waitFor: ['build-2']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['builds', 'submit', '--config', 'Codigo/YML_Publisher/CI-CD/cicd_yml_publisher.yaml', '.']
    id: 'build-7'
    waitFor: ['build-2']

  