steps:
  - name: 'hashicorp/terraform:1.6.6'
    args: ['init']
    dir: 'IaC/modules/storage'
    
  - name: 'hashicorp/terraform:1.6.6'
    args: ['apply', '-compact-warnings', '-auto-approve', '-var-file=../../environments/dev/main.tfvars']
    dir: 'IaC/modules/storage'

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - "BUCKET_NAME=$(grep name_functions_bucket ../../environments/dev/main.tfvars | cut -d '=' -f2 | tr -d '[:space:]')"

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'zip -r qid_publisher.zip ../../../Codigo/QID/qid_publisher'

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'zip -r qae_publisher.zip ../../../Codigo/QID/qae_publisher'

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'zip -r qae_notification.zip ../../../Codigo/QID/qae_notification'

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'zip -r yml_publisher.zip ../../../Codigo/QID/yml_publisher'

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'zip -r config_gs.zip ../../../Codigo/QID/config_gs'

  - name: 'gcr.io/cloud-builders/gsutil'
    args: 
      - 'cp'
      - 'qid_publisher.zip'
      - 'qae_publisher.zip'
      - 'qae_notification.zip'
      - 'yml_publisher.zip'
      - 'config_gs.zip'
      - '$BUCKET_NAME'
