steps:
  # Paso 1: Ejecutar las pruebas unitarias
  # - name: 'python:3.9'
  #   entrypoint: 'bash'
  #   id: testing_functions
  #   args:
  #     - '-c'
  #     - |
  #       pip install -r Codigo/Config_GS/config_gs/requirements.txt
  #       python -m unittest Codigo/Config_GS/test/test_config_gs.py

  # Paso 2: Desplegar la Cloud Function
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
            'functions', 'deploy', 'config_gs',
            '--region=europe-west3',
            '--source=Codigo/Config_GS/config_gs', 
            # '--trigger-http',
            # '--runtime=python39',
            # '--service-account=dataquality@diegucci-dq.iam.gserviceaccount.com',
            # '--set-secrets=DQ_KEY=data_quality_key:latest',
            # '--set-env-vars=MATRIX_FILE=MatrixInput_v1.1'
          ]
    # waitFor: ['testing_functions']

